export const properties = [
    {
      image: "/image1.png",
      address: "103/143 West Street, Crows Nest",
      bedrooms: 10,
      area: 150,
      garage: 2,
      builder: "X Builder",
      price: "$45,545",
    },
    {
      image: "/image1.png",
      address: "103/143 West Street, Crows Nest",
      bedrooms: 10,
      area: 150,
      garage: 2,
      builder: "X Builder",
      price: "$45,545",
    },
    {
      image: "/image1.png",
      address: "103/143 West Street, Crows Nest",
      bedrooms: 10,
      area: 150,
      garage: 2,
      builder: "X Builder",
      price: "$45,545",
    },
    {
      image: "/image1.png",
      address: "103/143 West Street, Crows Nest",
      bedrooms: 10,
      area: 150,
      garage: 2,
      builder: "X Builder",
      price: "$45,545",
    },
    {
      image: "/image1.png",
      address: "103/143 West Street, Crows Nest",
      bedrooms: 10,
      area: 150,
      garage: 2,
      builder: "X Builder",
      price: "$45,545",
    },
    {
      image: "/image1.png",
      address: "103/143 West Street, Crows Nest",
      bedrooms: 10,
      area: 150,
      garage: 2,
      builder: "X Builder",
      price: "$45,545",
    },
    {
      image: "/image1.png",
      address: "103/143 West Street, Crows Nest",
      bedrooms: 10,
      area: 150,
      garage: 2,
      builder: "X Builder",
      price: "$45,545",
    },
    {
      image: "/image1.png",
      address: "103/143 West Street, Crows Nest",
      bedrooms: 10,
      area: 150,
      garage: 2,
      builder: "X Builder",
      price: "$45,545",
    },
    {
      image: "/image1.png",
      address: "103/143 West Street, Crows Nest",
      bedrooms: 10,
      area: 150,
      garage: 2,
      builder: "X Builder",
      price: "$45,545",
    },
  ];
